apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskie.fullname" . }}-frontend
  labels:
    {{- include "taskie.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "taskie.selectorLabels" . | nindent 4 }}
    component: frontend
